/**
 * Rule-Based Extraction Engine
 * 
 * Fast pattern-matching engine that extracts events WITHOUT using LLM.
 * Used as the 2nd tier in the 3-tier architecture:
 * 
 * TIER 1: Heuristic Gate (keyword detection)
 * TIER 2: Rule Engine (pattern extraction) <-- THIS MODULE
 * TIER 3: LLM Extraction (complex cases)
 * 
 * The rule engine handles common, well-structured patterns like:
 * - "Meeting tomorrow at 3pm"
 * - "Call mom at 6"
 * - "Bring milk today"
 * - "Submit report by Friday"
 * 
 * If the rule engine can confidently extract an event, we skip the LLM.
 * This saves tokens, reduces latency, and is more reliable for simple cases.
 * 
 * AUTO-LEARNING: This engine also loads dynamically learned patterns from
 * the database that were generated by the PatternLearner service.
 */

import { ExtractedEvent, EventType } from '../types/index.js';
import { config } from '../config/index.js';
import logger from '../utils/logger.js';

// ==========================================
// DYNAMIC LEARNED PATTERNS (Auto-Learning)
// ==========================================

// Cached learned patterns (reloaded periodically)
let learnedPatterns: {
  time: { pattern: RegExp; id: string }[];
  date: { pattern: RegExp; id: string }[];
  action: { pattern: RegExp; id: string }[];
} = { time: [], date: [], action: [] };

let lastPatternLoad = 0;
const PATTERN_RELOAD_INTERVAL = 5 * 60 * 1000; // Reload every 5 minutes

// Pattern stats callback for updating hit/miss counts
let patternStatsCallback: ((patternId: string, hit: boolean) => void) | null = null;

/**
 * Set the callback for updating pattern stats (called by patternLearner)
 */
export function setPatternStatsCallback(callback: (patternId: string, hit: boolean) => void): void {
  patternStatsCallback = callback;
}

/**
 * Load learned patterns from the database
 * This is called lazily and cached
 */
export function loadLearnedPatterns(patterns: {
  time: { pattern: RegExp; id: string }[];
  date: { pattern: RegExp; id: string }[];
  action: { pattern: RegExp; id: string }[];
}): void {
  learnedPatterns = patterns;
  lastPatternLoad = Date.now();
  logger.info('Loaded learned patterns into rule engine', {
    time: patterns.time.length,
    date: patterns.date.length,
    action: patterns.action.length,
  });
}

/**
 * Check if patterns need reloading
 */
export function needsPatternReload(): boolean {
  return Date.now() - lastPatternLoad > PATTERN_RELOAD_INTERVAL;
}

/**
 * Get count of loaded learned patterns
 */
export function getLearnedPatternCounts(): { time: number; date: number; action: number } {
  return {
    time: learnedPatterns.time.length,
    date: learnedPatterns.date.length,
    action: learnedPatterns.action.length,
  };
}

export interface RuleEngineResult {
  success: boolean;
  confidence: number;
  event: ExtractedEvent | null;
  matchedPatterns: string[];
  skipLLM: boolean;
}

// Minimum confidence to skip LLM
const MIN_CONFIDENCE_TO_SKIP_LLM = 0.75;

// ==========================================
// TIME EXTRACTION PATTERNS
// ==========================================

// Explicit time patterns (high confidence)
const TIME_PATTERNS = {
  // 24-hour format: 14:30, 14.30
  time24: /\b(\d{1,2})[:\.](\d{2})\b/,
  
  // 12-hour format: 2:30 PM, 2:30pm, 2.30 am
  time12: /\b(\d{1,2})[:\.](\d{2})\s*(am|pm|a\.m\.|p\.m\.)\b/i,
  
  // Simple hour: 3pm, 3 pm, 3 AM
  simpleHour: /\b(\d{1,2})\s*(am|pm|a\.m\.|p\.m\.)\b/i,
  
  // O'clock: 3 o'clock, 3 oclock
  oclock: /\b(\d{1,2})\s*o'?clock\b/i,
  
  // Half past: half past 3, half past three
  halfPast: /\bhalf\s+past\s+(\d{1,2}|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve)\b/i,
  
  // Quarter past/to: quarter past 3, quarter to 5
  quarter: /\bquarter\s+(past|to)\s+(\d{1,2}|one|two|three|four|five|six|seven|eight|nine|ten|eleven|twelve)\b/i,
  
  // Relative: in 2 hours, in 30 minutes
  relative: /\bin\s+(\d+)\s*(hour|hr|minute|min|day|week)s?\b/i,
};

// Day patterns
const DAY_PATTERNS = {
  // Today, tomorrow, day after tomorrow
  today: /\b(today|aaj)\b/i,
  tomorrow: /\b(tomorrow|tmrw|tmr|tomo|kal)\b/i,
  dayAfter: /\b(day after tomorrow|parso|parson)\b/i,
  
  // Weekdays
  weekday: /\b(monday|tuesday|wednesday|thursday|friday|saturday|sunday|mon|tue|wed|thu|fri|sat|sun)\b/i,
  
  // This/next + weekday
  thisNext: /\b(this|next)\s+(monday|tuesday|wednesday|thursday|friday|saturday|sunday|week|month)\b/i,
  
  // Date formats: 25th, 25/12, Dec 25, December 25th, 15th March
  dateOrdinal: /\b(\d{1,2})(st|nd|rd|th)\b/i,
  dateSlash: /\b(\d{1,2})\/(\d{1,2})(\/\d{2,4})?\b/,
  dateMonth: /\b(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\s+(\d{1,2})(st|nd|rd|th)?\b/i,
  // Day first format: 15th March, 25 December
  dateDayMonth: /\b(\d{1,2})(st|nd|rd|th)?\s+(of\s+)?(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\b/i,
};

// Action patterns for event type detection
const ACTION_PATTERNS = {
  // Reminder actions
  remind: /\b(remind\s*(me|us)?|reminder|don'?t\s+forget|remember\s+to|yaad|bhool\s*mat)\b/i,
  
  // Meeting/call
  meeting: /\b(meeting|meet|call|catch\s*up|sync|1[:\-]1|one\s*on\s*one)\b/i,
  
  // Tasks/errands
  task: /\b(bring|get|buy|pick\s*up|drop\s*off|collect|fetch|submit|send|pay|return|deliver)\b/i,
  
  // Cancel/update
  cancel: /\b(cancel|cancelled|canceled|skip|drop|abort|call\s*off)\b/i,
  reschedule: /\b(reschedule|postpone|move\s+to|shift\s+to|delay|push\s+to|change\s+time)\b/i,
  
  // Deadline
  deadline: /\b(deadline|due|submit\s+by|due\s+by|by\s+\d|before\s+\d|submission)\b/i,
  
  // Academic events (exams, quizzes, assignments)
  academic: /\b(exam|exams|test|tests|quiz|quizzes|assignment|assignments|viva|presentation|project|homework|lab|practical|seminar|lecture|class|tutorial)\b/i,
};

// Word to number mapping
const WORD_TO_NUMBER: Record<string, number> = {
  'one': 1, 'two': 2, 'three': 3, 'four': 4, 'five': 5,
  'six': 6, 'seven': 7, 'eight': 8, 'nine': 9, 'ten': 10,
  'eleven': 11, 'twelve': 12,
};

// Day name to offset from today (calculated at runtime)
const WEEKDAY_MAP: Record<string, number> = {
  'sunday': 0, 'sun': 0,
  'monday': 1, 'mon': 1,
  'tuesday': 2, 'tue': 2,
  'wednesday': 3, 'wed': 3,
  'thursday': 4, 'thu': 4,
  'friday': 5, 'fri': 5,
  'saturday': 6, 'sat': 6,
};

const MONTH_MAP: Record<string, number> = {
  'jan': 0, 'january': 0,
  'feb': 1, 'february': 1,
  'mar': 2, 'march': 2,
  'apr': 3, 'april': 3,
  'may': 4,
  'jun': 5, 'june': 5,
  'jul': 6, 'july': 6,
  'aug': 7, 'august': 7,
  'sep': 8, 'september': 8,
  'oct': 9, 'october': 9,
  'nov': 10, 'november': 10,
  'dec': 11, 'december': 11,
};

/**
 * Main rule engine function
 * Attempts to extract event data using pattern matching
 */
export function extractWithRules(content: string, sender?: string): RuleEngineResult {
  // Skip if rule engine is disabled
  if (!config.enableRuleEngine) {
    return {
      success: false,
      confidence: 0,
      event: null,
      matchedPatterns: [],
      skipLLM: false,
    };
  }

  const normalizedContent = content.toLowerCase().trim();
  const matchedPatterns: string[] = [];
  let confidence = 0;

  logger.debug('Rule engine processing', { contentLength: normalizedContent.length });

  // Step 1: Detect event type
  const eventType = detectEventType(normalizedContent, matchedPatterns);
  if (eventType === 'irrelevant') {
    return {
      success: false,
      confidence: 0,
      event: null,
      matchedPatterns,
      skipLLM: false,
    };
  }
  confidence += 0.3;

  // Step 2: Extract time
  const extractedTime = extractTime(normalizedContent, matchedPatterns);
  if (extractedTime) {
    confidence += 0.3;
  }

  // Step 3: Extract date
  const extractedDate = extractDate(normalizedContent, matchedPatterns);
  if (extractedDate) {
    confidence += 0.2;
  }

  // Step 4: Combine date and time
  const startTime = combineDateTime(extractedDate, extractedTime);

  // Step 5: Extract title/action
  const title = extractTitle(normalizedContent, eventType);
  if (title) {
    confidence += 0.2;
  }

  // Step 6: Extract participants
  const participants = extractParticipants(content); // Use original case

  // Determine if we have enough confidence
  const skipLLM = confidence >= MIN_CONFIDENCE_TO_SKIP_LLM && startTime !== null;

  const event: ExtractedEvent = {
    event_type: eventType,
    title: title || generateDefaultTitle(eventType, content),
    start_time: startTime,
    end_time: null,
    condition: { type: null, value: null },
    participants,
    created_by: sender || null,
    confidence: Math.min(confidence, 0.95),
  };

  logger.info('Rule engine result', {
    success: skipLLM,
    confidence: Math.round(confidence * 100) / 100,
    eventType,
    title: event.title,
    startTime,
    matchedPatterns: matchedPatterns.length,
    skipLLM,
  });

  return {
    success: skipLLM,
    confidence,
    event,
    matchedPatterns,
    skipLLM,
  };
}

/**
 * Detects the event type from content
 */
function detectEventType(content: string, patterns: string[]): EventType {
  // Check for cancel/update first
  if (ACTION_PATTERNS.cancel.test(content)) {
    patterns.push('action:cancel');
    return 'update_event';
  }
  
  if (ACTION_PATTERNS.reschedule.test(content)) {
    patterns.push('action:reschedule');
    return 'update_event';
  }

  // Check for new event patterns
  if (ACTION_PATTERNS.remind.test(content)) {
    patterns.push('action:remind');
    return 'new_event';
  }

  if (ACTION_PATTERNS.meeting.test(content)) {
    patterns.push('action:meeting');
    return 'new_event';
  }

  if (ACTION_PATTERNS.task.test(content)) {
    patterns.push('action:task');
    return 'new_event';
  }

  if (ACTION_PATTERNS.deadline.test(content)) {
    patterns.push('action:deadline');
    return 'new_event';
  }

  if (ACTION_PATTERNS.academic.test(content)) {
    patterns.push('action:academic');
    return 'new_event';
  }

  // Check learned action patterns (auto-learning)
  for (const learned of learnedPatterns.action) {
    if (learned.pattern.test(content)) {
      patterns.push(`learned:action:${learned.id}`);
      if (patternStatsCallback) {
        patternStatsCallback(learned.id, true);
      }
      return 'new_event';
    }
  }

  // If we have time/date patterns, assume it's a new event
  const hasTime = Object.values(TIME_PATTERNS).some(p => p.test(content));
  const hasDate = Object.values(DAY_PATTERNS).some(p => p.test(content));
  
  // Also check learned time/date patterns
  const hasLearnedTime = learnedPatterns.time.some(p => p.pattern.test(content));
  const hasLearnedDate = learnedPatterns.date.some(p => p.pattern.test(content));
  
  if (hasTime || hasDate || hasLearnedTime || hasLearnedDate) {
    patterns.push('has_time_or_date');
    return 'new_event';
  }

  return 'irrelevant';
}

/**
 * Extracts time from content
 * Returns { hours: number, minutes: number } or null
 */
function extractTime(content: string, patterns: string[]): { hours: number; minutes: number } | null {
  // Try 12-hour format with minutes: 2:30 PM
  let match = content.match(TIME_PATTERNS.time12);
  if (match) {
    let hours = parseInt(match[1], 10);
    const minutes = parseInt(match[2], 10);
    const period = match[3].toLowerCase();
    
    if (period.startsWith('p') && hours < 12) hours += 12;
    if (period.startsWith('a') && hours === 12) hours = 0;
    
    patterns.push('time:12hour_with_minutes');
    return { hours, minutes };
  }

  // Try simple hour: 3pm
  match = content.match(TIME_PATTERNS.simpleHour);
  if (match) {
    let hours = parseInt(match[1], 10);
    const period = match[2].toLowerCase();
    
    if (period.startsWith('p') && hours < 12) hours += 12;
    if (period.startsWith('a') && hours === 12) hours = 0;
    
    patterns.push('time:simple_hour');
    return { hours, minutes: 0 };
  }

  // Try o'clock: 3 o'clock
  match = content.match(TIME_PATTERNS.oclock);
  if (match) {
    const hours = parseInt(match[1], 10);
    patterns.push('time:oclock');
    // Assume PM if between 1-6, AM otherwise (common pattern)
    return { hours: hours < 7 ? hours + 12 : hours, minutes: 0 };
  }

  // Try half past: half past 3
  match = content.match(TIME_PATTERNS.halfPast);
  if (match) {
    let hours = WORD_TO_NUMBER[match[1].toLowerCase()] || parseInt(match[1], 10);
    patterns.push('time:half_past');
    // Assume PM if between 1-6
    if (hours < 7) hours += 12;
    return { hours, minutes: 30 };
  }

  // Try quarter past/to
  match = content.match(TIME_PATTERNS.quarter);
  if (match) {
    const direction = match[1].toLowerCase();
    let hours = WORD_TO_NUMBER[match[2].toLowerCase()] || parseInt(match[2], 10);
    
    if (hours < 7) hours += 12;
    
    if (direction === 'past') {
      patterns.push('time:quarter_past');
      return { hours, minutes: 15 };
    } else {
      patterns.push('time:quarter_to');
      return { hours: hours - 1, minutes: 45 };
    }
  }

  // Try relative time: in 2 hours
  match = content.match(TIME_PATTERNS.relative);
  if (match) {
    const amount = parseInt(match[1], 10);
    const unit = match[2].toLowerCase();
    
    const now = new Date();
    
    if (unit.startsWith('hour') || unit.startsWith('hr')) {
      now.setHours(now.getHours() + amount);
      patterns.push('time:relative_hours');
      return { hours: now.getHours(), minutes: now.getMinutes() };
    }
    
    if (unit.startsWith('min')) {
      now.setMinutes(now.getMinutes() + amount);
      patterns.push('time:relative_minutes');
      return { hours: now.getHours(), minutes: now.getMinutes() };
    }
  }

  // Try 24-hour format: 14:30 (but be careful not to match dates like 25/12)
  match = content.match(TIME_PATTERNS.time24);
  if (match) {
    const hours = parseInt(match[1], 10);
    const minutes = parseInt(match[2], 10);
    
    if (hours <= 23 && minutes <= 59) {
      patterns.push('time:24hour');
      return { hours, minutes };
    }
  }

  // Try learned time patterns (auto-learning)
  // Note: Learned patterns can detect time but may not extract hours/minutes directly
  // This is a signal to increase confidence, actual extraction may still need enhancement
  for (const learned of learnedPatterns.time) {
    if (learned.pattern.test(content)) {
      patterns.push(`learned:time:${learned.id}`);
      if (patternStatsCallback) {
        patternStatsCallback(learned.id, true);
      }
      // For now, we just note the pattern matched
      // Full extraction requires pattern-specific logic
      break;
    }
  }

  return null;
}

/**
 * Extracts date from content
 * Returns a Date object or null
 */
function extractDate(content: string, patterns: string[]): Date | null {
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());

  // Today
  if (DAY_PATTERNS.today.test(content)) {
    patterns.push('date:today');
    return today;
  }

  // Tomorrow
  if (DAY_PATTERNS.tomorrow.test(content)) {
    patterns.push('date:tomorrow');
    const tomorrow = new Date(today);
    tomorrow.setDate(tomorrow.getDate() + 1);
    return tomorrow;
  }

  // Day after tomorrow
  if (DAY_PATTERNS.dayAfter.test(content)) {
    patterns.push('date:day_after_tomorrow');
    const dayAfter = new Date(today);
    dayAfter.setDate(dayAfter.getDate() + 2);
    return dayAfter;
  }

  // This/next + day: this friday, next monday
  let match = content.match(DAY_PATTERNS.thisNext);
  if (match) {
    const modifier = match[1].toLowerCase();
    const target = match[2].toLowerCase();
    
    if (WEEKDAY_MAP[target] !== undefined) {
      const targetDay = WEEKDAY_MAP[target];
      const currentDay = now.getDay();
      let daysAhead = targetDay - currentDay;
      
      if (modifier === 'next') {
        if (daysAhead <= 0) daysAhead += 7;
        daysAhead += 7; // Next week
      } else {
        if (daysAhead < 0) daysAhead += 7;
      }
      
      const result = new Date(today);
      result.setDate(result.getDate() + daysAhead);
      patterns.push(`date:${modifier}_${target}`);
      return result;
    }
  }

  // Weekday alone: friday, monday
  match = content.match(DAY_PATTERNS.weekday);
  if (match) {
    const dayName = match[1].toLowerCase();
    const targetDay = WEEKDAY_MAP[dayName];
    
    if (targetDay !== undefined) {
      const currentDay = now.getDay();
      let daysAhead = targetDay - currentDay;
      if (daysAhead <= 0) daysAhead += 7; // Next occurrence
      
      const result = new Date(today);
      result.setDate(result.getDate() + daysAhead);
      patterns.push(`date:weekday_${dayName}`);
      return result;
    }
  }

  // Date with month: Dec 25, December 25th
  match = content.match(DAY_PATTERNS.dateMonth);
  if (match) {
    const monthStr = match[1].toLowerCase();
    const day = parseInt(match[2], 10);
    const month = MONTH_MAP[monthStr.substring(0, 3)];
    
    if (month !== undefined && day >= 1 && day <= 31) {
      let year = now.getFullYear();
      const result = new Date(year, month, day);
      
      // If date is in past, assume next year
      if (result < today) {
        result.setFullYear(year + 1);
      }
      
      patterns.push('date:month_day');
      return result;
    }
  }

  // Date with day first: 15th March, 25 December, 15th of March
  match = content.match(DAY_PATTERNS.dateDayMonth);
  if (match) {
    const day = parseInt(match[1], 10);
    const monthStr = match[4].toLowerCase();
    const month = MONTH_MAP[monthStr.substring(0, 3)];
    
    if (month !== undefined && day >= 1 && day <= 31) {
      let year = now.getFullYear();
      const result = new Date(year, month, day);
      
      // If date is in past, assume next year
      if (result < today) {
        result.setFullYear(year + 1);
      }
      
      patterns.push('date:day_month');
      return result;
    }
  }

  // Date with slash: 25/12, 12/25
  match = content.match(DAY_PATTERNS.dateSlash);
  if (match) {
    const first = parseInt(match[1], 10);
    const second = parseInt(match[2], 10);
    
    // Try DD/MM format first (more common in India)
    let day = first;
    let month = second - 1;
    
    // If first number > 12, it must be DD/MM
    // If second number > 12, it must be MM/DD
    if (first > 12 && second <= 12) {
      day = first;
      month = second - 1;
    } else if (second > 12 && first <= 12) {
      day = second;
      month = first - 1;
    }
    
    if (month >= 0 && month <= 11 && day >= 1 && day <= 31) {
      let year = now.getFullYear();
      const result = new Date(year, month, day);
      
      if (result < today) {
        result.setFullYear(year + 1);
      }
      
      patterns.push('date:slash_format');
      return result;
    }
  }

  // Try learned date patterns (auto-learning)
  for (const learned of learnedPatterns.date) {
    if (learned.pattern.test(content)) {
      patterns.push(`learned:date:${learned.id}`);
      if (patternStatsCallback) {
        patternStatsCallback(learned.id, true);
      }
      // Note: Learned patterns signal date presence but may not provide exact date
      // This increases confidence for further processing
      break;
    }
  }

  // Default to today if we have a time but no explicit date
  // This will be handled in combineDateTime
  return null;
}

/**
 * Combines date and time into ISO string
 */
function combineDateTime(
  date: Date | null,
  time: { hours: number; minutes: number } | null
): string | null {
  if (!time && !date) {
    return null;
  }

  // Use IST timezone for interpretation, output UTC
  const istOffset = 5.5 * 60; // IST is UTC+5:30 in minutes
  
  const baseDate = date || new Date();
  const hours = time?.hours ?? 9; // Default to 9 AM if no time specified
  const minutes = time?.minutes ?? 0;

  // Create date in IST
  const istDate = new Date(
    baseDate.getFullYear(),
    baseDate.getMonth(),
    baseDate.getDate(),
    hours,
    minutes,
    0,
    0
  );

  // Convert IST to UTC
  const utcTime = new Date(istDate.getTime() - istOffset * 60 * 1000);

  // If the resulting time is in the past, add a day
  if (utcTime < new Date() && !date) {
    utcTime.setDate(utcTime.getDate() + 1);
  }

  return utcTime.toISOString();
}

/**
 * Extracts a title from the content
 */
function extractTitle(content: string, _eventType: EventType): string | null {
  // For tasks, try to extract the action + object
  const taskMatch = content.match(/\b(bring|get|buy|pick\s*up|drop\s*off|collect|submit|send|pay|return|call|meet)\s+(.+?)(?:\s+(at|by|before|tomorrow|today|on|in)|$)/i);
  if (taskMatch) {
    const action = taskMatch[1].trim();
    const object = taskMatch[2].trim();
    // Clean up the object
    const cleanObject = object.replace(/\b(at|by|before|tomorrow|today|on|in)\b.*/i, '').trim();
    if (cleanObject.length > 0 && cleanObject.length < 50) {
      return capitalizeFirst(action) + ' ' + cleanObject;
    }
  }

  // For meetings, try to extract "meeting with X" or "call with X"
  const meetingMatch = content.match(/\b(meeting|call|sync|catchup)\s+(with\s+)?([a-zA-Z]+)/i);
  if (meetingMatch) {
    const type = meetingMatch[1];
    const person = meetingMatch[3];
    return capitalizeFirst(type) + ' with ' + capitalizeFirst(person);
  }

  // For reminders, try to extract "remind me to X"
  const remindMatch = content.match(/\bremind\s*(me|us)?\s*(to\s+)?(.+?)(?:\s+(at|by|before|tomorrow|today|on|in)|$)/i);
  if (remindMatch && remindMatch[3]) {
    const task = remindMatch[3].trim();
    if (task.length > 0 && task.length < 50) {
      return 'Reminder: ' + capitalizeFirst(task);
    }
  }

  return null;
}

/**
 * Generates a default title based on event type
 */
function generateDefaultTitle(_eventType: EventType, content: string): string {
  const words = content.split(/\s+/).slice(0, 5).join(' ');
  return words.length > 3 ? capitalizeFirst(words) : 'Reminder';
}

/**
 * Extracts participant names from content
 */
function extractParticipants(content: string): string[] {
  const participants: string[] = [];
  
  // Look for "with X" patterns
  const withMatch = content.match(/\bwith\s+([A-Z][a-z]+)/);
  if (withMatch) {
    participants.push(withMatch[1]);
  }
  
  // Look for capitalized names (simple heuristic)
  const nameMatches = content.match(/\b([A-Z][a-z]{2,})\b/g);
  if (nameMatches) {
    for (const name of nameMatches) {
      // Skip common words that start with capital
      const skipWords = ['Meeting', 'Call', 'Today', 'Tomorrow', 'Monday', 'Tuesday', 'Wednesday', 
        'Thursday', 'Friday', 'Saturday', 'Sunday', 'January', 'February', 'March', 'April', 
        'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December',
        'Remind', 'Reminder', 'Submit', 'Send', 'Buy', 'Get', 'Pick', 'Drop', 'Bring'];
      
      if (!skipWords.includes(name) && !participants.includes(name)) {
        participants.push(name);
      }
    }
  }
  
  return participants.slice(0, 5); // Limit to 5 participants
}

/**
 * Capitalizes the first letter of a string
 */
function capitalizeFirst(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1).toLowerCase();
}

export default { 
  extractWithRules, 
  loadLearnedPatterns, 
  needsPatternReload,
  getLearnedPatternCounts,
  setPatternStatsCallback,
};
